name : Deploy test
on:
  push:
    branches:
      -"main"
    pull_request:
      -"main"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14,16,18]
      name: node ${{matrix.node}} version
      steps:
       - name: check repo
         uses: action/checkout@v2    
        
       - name: setup node version ${{matrix.node-version}}
         uses: action/checkout@v1
         with:
            node-version: ${{matrix.node-version}}

       - name: Install packages
          run: npm install

       - name: run build
          run: npm run3 build 
            